target-examples:; @true
target-src/infra/log:; @true
target-src/infra/system:; @true
target-src/infra/utils:; @true
target-src/protocol/alcs:; @true
target-src/protocol/coap:; @true
target-src/protocol/http:; @true
target-src/protocol/http2:; @true
target-src/protocol/mqtt:; @true
target-src/ref-impl/hal:; @true
target-src/ref-impl/tls:; @true
target-src/sdk-impl:; @true
target-src/services/awss:; @true
target-src/services/file_upload:; @true
target-src/services/linkkit/cm:; @true
target-src/services/linkkit/dm:; @true
target-src/services/shadow:; @true
target-src/services/subdev:; @true
target-src/services/uOTA:; @true
target-src/tools/linkkit_tsl_convert:; @true
target-tests:; @true
